#Requires -Version 5.0
#Requires -Modules @{ModuleName = "microsoftteams"; ModuleVersion = "1.0.3"}

<#
.SYNOPSIS
    Returns app information from the Teams tenant app store

.DESCRIPTION

.NOTES
    This PowerShell script was developed and optimized for ScriptRunner. The use of the scripts requires ScriptRunner. 
    The customer or user is authorized to copy the script from the repository and use them in ScriptRunner. 
    The terms of use for ScriptRunner do not apply to this script. In particular, ScriptRunner Software GmbH assumes no liability for the function, 
    the use and the consequences of the use of this freely available script.
    PowerShell is a product of Microsoft Corporation. ScriptRunner is a product of ScriptRunner Software GmbH.
    © ScriptRunner Software GmbH

.COMPONENT
    Requires Module microsoftteams 1.0.3 or greater
    Requires .NET Framework Version 4.7.2.
    Requires Library script MSTLibrary.ps1

.LINK
    https://github.com/scriptrunner/ActionPacks/tree/master/O365/MS-Teams/Apps
 
.Parameter MSTCredential
    Provides the user ID and password for organizational ID credentials

.Parameter AppId
    The app's ID generated by Teams (different from the external ID)

.Parameter ExternalID
    The external ID of the app, provided by the app developer and used by Azure Active Directory
    
.Parameter DisplayName
    Name of the app visible to users

.Parameter DistributionMethod    
    The type of app in Teams. For LOB apps, use "organization"

.Parameter TenantID
    Specifies the ID of a tenant
#>

[CmdLetBinding()]
Param(
    [Parameter(Mandatory = $true)]   
    [pscredential]$MSTCredential,
    [string]$AppId,
    [string]$ExternalID,
    [string]$DisplayName,
    [ValidateSet('organization','global')]
    [string]$DistributionMethod,
    [string]$TenantID
)

Import-Module microsoftteams

try{
    ConnectMSTeams -MTCredential $MSTCredential -TenantID $TenantID

    [hashtable]$cmdArgs = @{'ErrorAction' = 'Stop'}

    if($PSBoundParameters.ContainsKey('AppId')){
        $cmdArgs.Add('Id',$AppId)
    } 
    if($PSBoundParameters.ContainsKey('ExternalID')){
        $cmdArgs.Add('ExternalID',$ExternalID)
    } 
    if($PSBoundParameters.ContainsKey('DisplayName')){
        $cmdArgs.Add('DisplayName',$DisplayName)
    } 
    if($PSBoundParameters.ContainsKey('DistributionMethod')){
        $cmdArgs.Add('DistributionMethod',$DistributionMethod)
    } 

    $result = Get-TeamsApp @cmdArgs | Select-Object * | Sort-Object -Property DisplayName
    
    if($SRXEnv) {
        $SRXEnv.ResultMessage = $result
    }
    else{
        Write-Output $result
    }
}
catch{
    throw
}
finally{
    DisconnectMSTeams
}